# Generated by Django 2.2.5 on 2019-09-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuit',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
