# Generated by Django 2.2.5 on 2019-09-13 08:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('circuit', '0002_auto_20190913_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuit',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False,
                                   primary_key=True, serialize=False),
        ),
    ]
