# Generated by Django 2.2.5 on 2019-09-13 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True,
                                        serialize=False)),
                ('name', models.CharField(max_length=48)),
                ('ip', models.GenericIPAddressField()),
                ('type', models.CharField(max_length=48)),
                ('software', models.CharField(blank=True, max_length=48)),
                ('serial', models.CharField(blank=True, max_length=48)),
                ('data_usage', models.CharField(blank=True, max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tms_uuid', models.ForeignKey(on_delete=django.db.models.
                                               deletion.CASCADE,
                                               to='tms.TMS')),
            ],
            options={
                'unique_together': {('tms_uuid', 'id')},
            },
        ),
    ]
