# Generated by Django 2.2.5 on 2019-09-13 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMS',
            fields=[
                ('id', models.CharField(primary_key=True, max_length=36,
                                        serialize=False)),
                ('host', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=48)),
                ('dailyreporter_version', models.CharField(blank=True,
                                                           max_length=24)),
                ('tms_version', models.CharField(max_length=24)),
                ('tmsconnect_version', models.CharField(blank=True,
                                                        max_length=24)),
                ('country', models.CharField(blank=True, max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_uuid', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to='contact.Contact')),
            ],
        ),
    ]
